force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InterviewReminderBatch.cls
// Batch job to generate reminder Tasks for interviews happening tomorrow.
public class InterviewReminderBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date tomorrow = Date.today().addDays(1);
        
        return Database.getQueryLocator([
            SELECT Id, Name, Applicant__r.Email__c 
            FROM Application__c 
            WHERE Interview_Date__c = :tomorrow
        ]);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<Task> reminders = new List<Task>();
        
        List<Application__c> apps = (List<Application__c>) scope;
        
        for (Application__c app : apps) {
            reminders.add(new Task(
                Subject = 'Upcoming Interview Reminder',
                WhatId = app.Id, 
                ActivityDate = Date.today(),
                Priority = 'High',
                Status = 'Not Started'
            ));
        }
        
        if (!reminders.isEmpty()) {
            insert reminders;
        }
    }

    public void finish(Database.BatchableContext bc) {
        
    }
}